
package com.joseluis.apptaller.vista.ventanas;

import com.joseluis.apptaller.vista.dialogos.DialogDetallesReparacion;
import com.joseluis.apptaller.vista.dialogos.DialogHistorialCliente;
import com.joseluis.apptaller.vista.dialogos.DialogNuevaReparacion;
import com.joseluis.apptaller.vista.dialogos.DialogPresupuesto;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.UIManager;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import mdlaf.MaterialLookAndFeel;
import mdlaf.themes.MaterialLiteTheme;

/**
 *
 * @author joseluis
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        setTitle("APP MI TALLER");
        setSize(1200, 800);
        //setIconImage("images/logo_apptaller_titulo.ico");
        setLocationRelativeTo(null);
        lstAyuda.setFixedCellHeight(35);
        
        iniciarReloj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelTitulo = new javax.swing.JPanel();
        etqLogo = new javax.swing.JLabel();
        etqTitulo = new javax.swing.JLabel();
        panelNavegacion = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnVehiculos = new javax.swing.JButton();
        btnReparaciones = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnPresupuestos = new javax.swing.JButton();
        btnFacturas = new javax.swing.JButton();
        btnEmpleados = new javax.swing.JButton();
        btnAyuda = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelPrincipal = new javax.swing.JPanel();
        panelInicio = new javax.swing.JPanel();
        panelBienvenida = new javax.swing.JPanel();
        etqBienvenida = new javax.swing.JLabel();
        etqReloj = new javax.swing.JLabel();
        panelEstadoTaller = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelAgenda = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        panelStock = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel6 = new javax.swing.JLabel();
        panelInferior = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        panelClientes = new javax.swing.JPanel();
        panelHerramientas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnInforme = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        panelVehiculos = new javax.swing.JPanel();
        panelHerramientasVehiculos = new javax.swing.JPanel();
        etqGestionVehiculos = new javax.swing.JLabel();
        txtBuscarVehiculo = new javax.swing.JTextField();
        btnBuscarVehiculo = new javax.swing.JButton();
        btnNuevoVehiculo = new javax.swing.JButton();
        btnInformeVehiculo = new javax.swing.JButton();
        btnEliminarVehiculo = new javax.swing.JButton();
        jScrollPaneVehiculos = new javax.swing.JScrollPane();
        tblVehiculo = new javax.swing.JTable();
        panelReparaciones = new javax.swing.JPanel();
        panelIndicadores = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        panelCuerpo = new javax.swing.JPanel();
        panelBarraHerramientas = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        panelProveedores = new javax.swing.JPanel();
        panelHerramientasProveedores = new javax.swing.JPanel();
        etqGestionProveedores = new javax.swing.JLabel();
        txtBuscarProveedores = new javax.swing.JTextField();
        btnBuscarProveedores = new javax.swing.JButton();
        btnNuevoProveedores = new javax.swing.JButton();
        btnInformeProveedores = new javax.swing.JButton();
        btnEliminarProveedores = new javax.swing.JButton();
        jScrollPaneProveedores = new javax.swing.JScrollPane();
        tblProveedores = new javax.swing.JTable();
        panelProductos = new javax.swing.JPanel();
        panelHerramientasProductos = new javax.swing.JPanel();
        etqGestionProductos = new javax.swing.JLabel();
        txtBuscarProductos = new javax.swing.JTextField();
        btnBuscarProductos = new javax.swing.JButton();
        btnNuevoProductos = new javax.swing.JButton();
        btnInformeProductos = new javax.swing.JButton();
        btnEliminarProductos = new javax.swing.JButton();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        panelPresupuestos = new javax.swing.JPanel();
        panelHerramientasPresupuestos = new javax.swing.JPanel();
        etqGestionPresupuestos = new javax.swing.JLabel();
        txtBuscarPresupuestos = new javax.swing.JTextField();
        btnBuscarPresupuestos = new javax.swing.JButton();
        btnNuevoPresupuestos = new javax.swing.JButton();
        btnInformePresupuestos = new javax.swing.JButton();
        btnEliminarPresupuestos = new javax.swing.JButton();
        jScrollPanePresupuestos = new javax.swing.JScrollPane();
        tblPresupuestos = new javax.swing.JTable();
        panelFacturas = new javax.swing.JPanel();
        panelHerramientasFacturas = new javax.swing.JPanel();
        etqGestionFacturas = new javax.swing.JLabel();
        txtBuscarFacturas = new javax.swing.JTextField();
        btnBuscarFacturas = new javax.swing.JButton();
        btnNuevoFacturas = new javax.swing.JButton();
        btnInformeFacturas = new javax.swing.JButton();
        btnEliminarFacturas = new javax.swing.JButton();
        jScrollPaneFacturas = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        panelEmpleados = new javax.swing.JPanel();
        panelHerramientasEmpleados = new javax.swing.JPanel();
        etqGestionEmpleados = new javax.swing.JLabel();
        txtBuscarEmpleado = new javax.swing.JTextField();
        btnBuscarEmpleado = new javax.swing.JButton();
        btnNuevoEmpleado = new javax.swing.JButton();
        btnInformeEmpleado = new javax.swing.JButton();
        btnEliminarEmpleado = new javax.swing.JButton();
        jScrollPaneClientes1 = new javax.swing.JScrollPane();
        tblClientes1 = new javax.swing.JTable();
        panelAyuda = new javax.swing.JPanel();
        panelCabeceraAyuda = new javax.swing.JPanel();
        etqTituloAyuda = new javax.swing.JLabel();
        etqBuscarAyuda = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstAyuda = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1200, 800));

        panelTitulo.setBackground(new java.awt.Color(33, 150, 243));

        etqLogo.setIcon(new javax.swing.ImageIcon("/mnt/0FEC087D0FEC087D/ProyectoDAM/Proyecto-DAM-Taller/AppTaller/src/main/resources/images/logo_apptaller_small.png")); // NOI18N

        etqTitulo.setFont(new java.awt.Font("Roboto", 1, 48)); // NOI18N
        etqTitulo.setForeground(new java.awt.Color(255, 255, 255));
        etqTitulo.setText("APP MI TALLER - INICIO");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(etqLogo)
                .addGap(191, 191, 191)
                .addComponent(etqTitulo)
                .addGap(0, 483, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etqLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etqTitulo)
                .addGap(22, 22, 22))
        );

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        panelNavegacion.setBackground(new java.awt.Color(250, 250, 250));
        panelNavegacion.setPreferredSize(new java.awt.Dimension(180, 100));
        panelNavegacion.setLayout(new java.awt.GridLayout(11, 0, 0, 5));

        btnInicio.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_home_48.png"))); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnInicio);

        btnClientes.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_azul_50dp.png"))); // NOI18N
        btnClientes.setText("Clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnClientes);

        btnVehiculos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_coche_50..png"))); // NOI18N
        btnVehiculos.setText("Vehículos");
        btnVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVehiculosActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnVehiculos);

        btnReparaciones.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnReparaciones.setText("Reparaciones");
        btnReparaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReparacionesActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnReparaciones);

        btnProveedores.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnProveedores.setText("Proveedores");
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnProveedores);

        btnProductos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnProductos.setText("Productos");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnProductos);

        btnPresupuestos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnPresupuestos.setText("Presupuestos");
        btnPresupuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPresupuestosActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnPresupuestos);

        btnFacturas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnFacturas.setText("Facturas");
        btnFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturasActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnFacturas);

        btnEmpleados.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnEmpleados.setText("Empleados");
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnEmpleados);

        btnAyuda.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnAyuda.setText("Ayuda");
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnAyuda);

        btnSalir.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        panelNavegacion.add(btnSalir);

        getContentPane().add(panelNavegacion, java.awt.BorderLayout.LINE_START);

        panelPrincipal.setBackground(new java.awt.Color(250, 250, 250));
        panelPrincipal.setLayout(new java.awt.CardLayout());

        panelInicio.setBackground(new java.awt.Color(245, 245, 245));
        panelInicio.setLayout(new java.awt.GridBagLayout());

        panelBienvenida.setBackground(new java.awt.Color(255, 255, 255));
        panelBienvenida.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        panelBienvenida.setMinimumSize(new java.awt.Dimension(100, 100));
        panelBienvenida.setPreferredSize(new java.awt.Dimension(0, 100));
        panelBienvenida.setLayout(new java.awt.BorderLayout(0, 20));

        etqBienvenida.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        etqBienvenida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_cliente_128.png"))); // NOI18N
        etqBienvenida.setText("BIENVENIDO, JOSÉ LUIS");
        panelBienvenida.add(etqBienvenida, java.awt.BorderLayout.LINE_START);

        etqReloj.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        etqReloj.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        etqReloj.setText("Cargando fecha...");
        etqReloj.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 20));
        panelBienvenida.add(etqReloj, java.awt.BorderLayout.LINE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        gridBagConstraints.weightx = 1.0;
        panelInicio.add(panelBienvenida, gridBagConstraints);

        panelEstadoTaller.setBackground(new java.awt.Color(255, 255, 255));
        panelEstadoTaller.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        panelEstadoTaller.setMinimumSize(new java.awt.Dimension(100, 150));
        panelEstadoTaller.setPreferredSize(new java.awt.Dimension(100, 280));
        panelEstadoTaller.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("5");
        panelEstadoTaller.add(jLabel3, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Vehículos en Taller");
        panelEstadoTaller.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelInicio.add(panelEstadoTaller, gridBagConstraints);

        panelAgenda.setBackground(new java.awt.Color(255, 255, 255));
        panelAgenda.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        panelAgenda.setMinimumSize(new java.awt.Dimension(100, 150));
        panelAgenda.setPreferredSize(new java.awt.Dimension(100, 280));
        panelAgenda.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        jList1.setBorder(null);
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "* 10:00 - Ford Fiesta (cambio de aceite)", "* 11:30 - Seat Arona - revisión 30000 km", "* 13:00 - Fiat Punto - cambio de neumáticos", "* 15:00 - Audi A3 - cambio alternador", "* 16:30 - Reanult Captur - cambio limpiaparabrisas" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        panelAgenda.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Agenda del día");
        panelAgenda.add(jLabel5, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelInicio.add(panelAgenda, gridBagConstraints);

        panelStock.setBackground(new java.awt.Color(255, 255, 255));
        panelStock.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        panelStock.setMinimumSize(new java.awt.Dimension(100, 150));
        panelStock.setPreferredSize(new java.awt.Dimension(100, 280));
        panelStock.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        panelStock.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Stock");
        panelStock.add(jLabel6, java.awt.BorderLayout.PAGE_END);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.33;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        panelInicio.add(panelStock, gridBagConstraints);

        panelInferior.setBackground(new java.awt.Color(255, 255, 255));
        panelInferior.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(224, 224, 224)), javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10)));
        panelInferior.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 13)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Notas Rápidas / Tareas");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        panelInferior.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jScrollPane3.setBorder(null);

        jTextArea1.setBackground(new java.awt.Color(255, 255, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("atehdzyhsxtumgfvoh.jb..\ncfjycg ,fivoñ-pj\nchm hif,hi.o-hipKnLug ");
        jScrollPane3.setViewportView(jTextArea1);

        panelInferior.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        panelInicio.add(panelInferior, gridBagConstraints);

        panelPrincipal.add(panelInicio, "cardInicio");

        panelClientes.setBackground(new java.awt.Color(250, 250, 250));
        panelClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelClientes.setLayout(new java.awt.BorderLayout());

        panelHerramientas.setBackground(new java.awt.Color(255, 255, 255));
        panelHerramientas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel1.setText("Gestión de Clientes");
        panelHerramientas.add(jLabel1);

        txtBuscar.setColumns(20);
        txtBuscar.setToolTipText("Buscar por nombre o DNI");
        txtBuscar.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 150, 243)));
        panelHerramientas.add(txtBuscar);

        btnBuscar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setFocusPainted(false);
        panelHerramientas.add(btnBuscar);

        btnNuevo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnNuevo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setFocusPainted(false);
        panelHerramientas.add(btnNuevo);

        btnInforme.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnInforme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        btnInforme.setText("Informe");
        btnInforme.setFocusPainted(false);
        panelHerramientas.add(btnInforme);

        jButton5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        jButton5.setText("Historial");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelHerramientas.add(jButton5);

        btnEliminar.setBackground(new java.awt.Color(229, 57, 53));
        btnEliminar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setFocusPainted(false);
        panelHerramientas.add(btnEliminar);

        panelClientes.add(panelHerramientas, java.awt.BorderLayout.PAGE_START);

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellidos", "Dirección", "Teléfono", "Email"
            }
        ));
        jScrollPaneClientes.setViewportView(tblClientes);

        panelClientes.add(jScrollPaneClientes, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelClientes, "cardClientes");

        panelVehiculos.setBackground(new java.awt.Color(250, 250, 250));
        panelVehiculos.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelVehiculos.setLayout(new java.awt.BorderLayout());

        panelHerramientasVehiculos.setBackground(new java.awt.Color(255, 255, 255));
        panelHerramientasVehiculos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        etqGestionVehiculos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        etqGestionVehiculos.setText("Gestión de Vehículos");
        panelHerramientasVehiculos.add(etqGestionVehiculos);

        txtBuscarVehiculo.setColumns(20);
        txtBuscarVehiculo.setToolTipText("Buscar por nombre o DNI");
        txtBuscarVehiculo.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 150, 243)));
        panelHerramientasVehiculos.add(txtBuscarVehiculo);

        btnBuscarVehiculo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnBuscarVehiculo.setText("Buscar");
        panelHerramientasVehiculos.add(btnBuscarVehiculo);

        btnNuevoVehiculo.setBackground(new java.awt.Color(33, 150, 243));
        btnNuevoVehiculo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnNuevoVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoVehiculo.setText("Nuevo");
        panelHerramientasVehiculos.add(btnNuevoVehiculo);

        btnInformeVehiculo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnInformeVehiculo.setText("Informe");
        panelHerramientasVehiculos.add(btnInformeVehiculo);

        btnEliminarVehiculo.setBackground(new java.awt.Color(229, 57, 53));
        btnEliminarVehiculo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnEliminarVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarVehiculo.setText("Eliminar");
        panelHerramientasVehiculos.add(btnEliminarVehiculo);

        panelVehiculos.add(panelHerramientasVehiculos, java.awt.BorderLayout.PAGE_START);

        tblVehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Bastidor", "Matrícula", "Marca", "Modelo", "Color"
            }
        ));
        jScrollPaneVehiculos.setViewportView(tblVehiculo);

        panelVehiculos.add(jScrollPaneVehiculos, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelVehiculos, "cardVehiculos");

        panelReparaciones.setLayout(new java.awt.BorderLayout());

        panelIndicadores.setPreferredSize(new java.awt.Dimension(0, 80));
        panelIndicadores.setLayout(new java.awt.GridLayout(1, 5, 10, 0));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("5");

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Prioridad 1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel2)))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        panelIndicadores.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(0, 51, 204));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("3");

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Prioridad 2");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel9)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        panelIndicadores.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("2");

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Prioridad 3");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel11)))
                .addGap(91, 91, 91))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        panelIndicadores.add(jPanel5);

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("1");

        jLabel14.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Prioridad 4");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel13)))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        panelIndicadores.add(jPanel2);

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("0");

        jLabel16.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Prioridad 5");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(97, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(28, 28, 28)))
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addContainerGap())
        );

        panelIndicadores.add(jPanel1);

        panelReparaciones.add(panelIndicadores, java.awt.BorderLayout.PAGE_START);

        panelCuerpo.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Nueva");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelBarraHerramientas.add(jButton1);

        jButton2.setText("Detalles");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelBarraHerramientas.add(jButton2);

        jButton3.setText("Estado");
        panelBarraHerramientas.add(jButton3);

        jButton4.setText("Asignar");
        panelBarraHerramientas.add(jButton4);

        jLabel17.setText("Filtrar estado: ");
        panelBarraHerramientas.add(jLabel17);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TODOS", "EN_COLA", "EN_PROCESO", "FINALIZADA" }));
        panelBarraHerramientas.add(jComboBox1);

        panelCuerpo.add(panelBarraHerramientas, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"REP-001", "Ford Fiesta", "Juan Pérez", "Carlos M.", "ALTA", "EN_PROCESO", "20/11/2025"},
                {"REP-002", "Audi A3", "Ana Gomez", "--", "MEDIA", "EN_COLA", "21/11/2025"},
                {"REP-003", "Seat León", "Pedro Ruiz", "Carlos M.", "BAJA", "FINALIZADA", "19/11/2025"},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Vehículo", "Cliente", "Mecánico", "Prioridad", "Estado", "Fecha Entrada"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        panelCuerpo.add(jScrollPane6, java.awt.BorderLayout.CENTER);

        panelReparaciones.add(panelCuerpo, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelReparaciones, "cardReparaciones");

        panelProveedores.setBackground(new java.awt.Color(250, 250, 250));
        panelProveedores.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelProveedores.setLayout(new java.awt.BorderLayout());

        panelHerramientasProveedores.setBackground(new java.awt.Color(255, 255, 255));
        panelHerramientasProveedores.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        etqGestionProveedores.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        etqGestionProveedores.setText("Gestión de Proveedores");
        panelHerramientasProveedores.add(etqGestionProveedores);

        txtBuscarProveedores.setColumns(20);
        txtBuscarProveedores.setToolTipText("Buscar por nombre o DNI");
        txtBuscarProveedores.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 150, 243)));
        panelHerramientasProveedores.add(txtBuscarProveedores);

        btnBuscarProveedores.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnBuscarProveedores.setText("Buscar");
        panelHerramientasProveedores.add(btnBuscarProveedores);

        btnNuevoProveedores.setBackground(new java.awt.Color(33, 150, 243));
        btnNuevoProveedores.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnNuevoProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProveedores.setText("Nuevo");
        panelHerramientasProveedores.add(btnNuevoProveedores);

        btnInformeProveedores.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnInformeProveedores.setText("Informe");
        panelHerramientasProveedores.add(btnInformeProveedores);

        btnEliminarProveedores.setBackground(new java.awt.Color(229, 57, 53));
        btnEliminarProveedores.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnEliminarProveedores.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProveedores.setText("Eliminar");
        panelHerramientasProveedores.add(btnEliminarProveedores);

        panelProveedores.add(panelHerramientasProveedores, java.awt.BorderLayout.PAGE_START);

        tblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI / CIF", "Empresa", "Contacto", "Teléfono", "Email", "Especialidad"
            }
        ));
        jScrollPaneProveedores.setViewportView(tblProveedores);

        panelProveedores.add(jScrollPaneProveedores, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelProveedores, "cardProveedores");

        panelProductos.setBackground(new java.awt.Color(250, 250, 250));
        panelProductos.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelProductos.setLayout(new java.awt.BorderLayout());

        panelHerramientasProductos.setBackground(new java.awt.Color(255, 255, 255));
        panelHerramientasProductos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        etqGestionProductos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        etqGestionProductos.setText("Gestión de Productos");
        panelHerramientasProductos.add(etqGestionProductos);

        txtBuscarProductos.setColumns(20);
        txtBuscarProductos.setToolTipText("Buscar por nombre o DNI");
        txtBuscarProductos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 150, 243)));
        panelHerramientasProductos.add(txtBuscarProductos);

        btnBuscarProductos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnBuscarProductos.setText("Buscar");
        panelHerramientasProductos.add(btnBuscarProductos);

        btnNuevoProductos.setBackground(new java.awt.Color(33, 150, 243));
        btnNuevoProductos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnNuevoProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProductos.setText("Nuevo");
        panelHerramientasProductos.add(btnNuevoProductos);

        btnInformeProductos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnInformeProductos.setText("Informe");
        panelHerramientasProductos.add(btnInformeProductos);

        btnEliminarProductos.setBackground(new java.awt.Color(229, 57, 53));
        btnEliminarProductos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnEliminarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarProductos.setText("Eliminar");
        panelHerramientasProductos.add(btnEliminarProductos);

        panelProductos.add(panelHerramientasProductos, java.awt.BorderLayout.PAGE_START);

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID / Referencia", "Descripción", "Categoría", "Precio coste", "PVP venta", "Stock"
            }
        ));
        jScrollPaneProductos.setViewportView(tblProductos);

        panelProductos.add(jScrollPaneProductos, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelProductos, "cardProductos");

        panelPresupuestos.setBackground(new java.awt.Color(250, 250, 250));
        panelPresupuestos.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelPresupuestos.setLayout(new java.awt.BorderLayout());

        panelHerramientasPresupuestos.setBackground(new java.awt.Color(255, 255, 255));
        panelHerramientasPresupuestos.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        etqGestionPresupuestos.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        etqGestionPresupuestos.setText("Gestión de Presupuestos");
        panelHerramientasPresupuestos.add(etqGestionPresupuestos);

        txtBuscarPresupuestos.setColumns(20);
        txtBuscarPresupuestos.setToolTipText("Buscar por nombre o DNI");
        txtBuscarPresupuestos.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 150, 243)));
        panelHerramientasPresupuestos.add(txtBuscarPresupuestos);

        btnBuscarPresupuestos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnBuscarPresupuestos.setText("Buscar");
        panelHerramientasPresupuestos.add(btnBuscarPresupuestos);

        btnNuevoPresupuestos.setBackground(new java.awt.Color(33, 150, 243));
        btnNuevoPresupuestos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnNuevoPresupuestos.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoPresupuestos.setText("Nuevo");
        btnNuevoPresupuestos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoPresupuestosActionPerformed(evt);
            }
        });
        panelHerramientasPresupuestos.add(btnNuevoPresupuestos);

        btnInformePresupuestos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnInformePresupuestos.setText("Informe");
        panelHerramientasPresupuestos.add(btnInformePresupuestos);

        btnEliminarPresupuestos.setBackground(new java.awt.Color(229, 57, 53));
        btnEliminarPresupuestos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnEliminarPresupuestos.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPresupuestos.setText("Eliminar");
        panelHerramientasPresupuestos.add(btnEliminarPresupuestos);

        panelPresupuestos.add(panelHerramientasPresupuestos, java.awt.BorderLayout.PAGE_START);

        tblPresupuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº Presupuesto", "Fecha", "Cliente", "Vehículo", "Total (€)", "Estado (Pendiente/Aceptado)"
            }
        ));
        jScrollPanePresupuestos.setViewportView(tblPresupuestos);

        panelPresupuestos.add(jScrollPanePresupuestos, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelPresupuestos, "cardPresupuestos");

        panelFacturas.setBackground(new java.awt.Color(250, 250, 250));
        panelFacturas.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelFacturas.setLayout(new java.awt.BorderLayout());

        panelHerramientasFacturas.setBackground(new java.awt.Color(255, 255, 255));
        panelHerramientasFacturas.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        etqGestionFacturas.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        etqGestionFacturas.setText("Gestión de Facturas");
        panelHerramientasFacturas.add(etqGestionFacturas);

        txtBuscarFacturas.setColumns(20);
        txtBuscarFacturas.setToolTipText("Buscar por nombre o DNI");
        txtBuscarFacturas.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 150, 243)));
        panelHerramientasFacturas.add(txtBuscarFacturas);

        btnBuscarFacturas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnBuscarFacturas.setText("Buscar");
        panelHerramientasFacturas.add(btnBuscarFacturas);

        btnNuevoFacturas.setBackground(new java.awt.Color(33, 150, 243));
        btnNuevoFacturas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnNuevoFacturas.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoFacturas.setText("Nuevo");
        panelHerramientasFacturas.add(btnNuevoFacturas);

        btnInformeFacturas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnInformeFacturas.setText("Informe");
        panelHerramientasFacturas.add(btnInformeFacturas);

        btnEliminarFacturas.setBackground(new java.awt.Color(229, 57, 53));
        btnEliminarFacturas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnEliminarFacturas.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFacturas.setText("Eliminar");
        panelHerramientasFacturas.add(btnEliminarFacturas);

        panelFacturas.add(panelHerramientasFacturas, java.awt.BorderLayout.PAGE_START);

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº Factura", "Fecha", "Cliente", "Base imponible", "IVA", "Total (€)"
            }
        ));
        jScrollPaneFacturas.setViewportView(tblFacturas);

        panelFacturas.add(jScrollPaneFacturas, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelFacturas, "cardFacturas");

        panelEmpleados.setBackground(new java.awt.Color(250, 250, 250));
        panelEmpleados.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        panelEmpleados.setLayout(new java.awt.BorderLayout());

        panelHerramientasEmpleados.setBackground(new java.awt.Color(255, 255, 255));
        panelHerramientasEmpleados.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 15, 5));

        etqGestionEmpleados.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        etqGestionEmpleados.setText("Gestión de Empleados");
        panelHerramientasEmpleados.add(etqGestionEmpleados);

        txtBuscarEmpleado.setColumns(20);
        txtBuscarEmpleado.setToolTipText("Buscar por nombre o DNI");
        txtBuscarEmpleado.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(33, 150, 243)));
        panelHerramientasEmpleados.add(txtBuscarEmpleado);

        btnBuscarEmpleado.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnBuscarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        btnBuscarEmpleado.setText("Buscar");
        btnBuscarEmpleado.setFocusPainted(false);
        panelHerramientasEmpleados.add(btnBuscarEmpleado);

        btnNuevoEmpleado.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnNuevoEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        btnNuevoEmpleado.setText("Nuevo");
        btnNuevoEmpleado.setFocusPainted(false);
        panelHerramientasEmpleados.add(btnNuevoEmpleado);

        btnInformeEmpleado.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnInformeEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        btnInformeEmpleado.setText("Informe");
        btnInformeEmpleado.setFocusPainted(false);
        panelHerramientasEmpleados.add(btnInformeEmpleado);

        btnEliminarEmpleado.setBackground(new java.awt.Color(229, 57, 53));
        btnEliminarEmpleado.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnEliminarEmpleado.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_persona_24dp.png"))); // NOI18N
        btnEliminarEmpleado.setText("Eliminar");
        btnEliminarEmpleado.setFocusPainted(false);
        panelHerramientasEmpleados.add(btnEliminarEmpleado);

        panelEmpleados.add(panelHerramientasEmpleados, java.awt.BorderLayout.PAGE_START);

        tblClientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Apellidos", "Dirección", "Teléfono", "Email"
            }
        ));
        jScrollPaneClientes1.setViewportView(tblClientes1);

        panelEmpleados.add(jScrollPaneClientes1, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelEmpleados, "cardEmpleados");

        panelAyuda.setBackground(new java.awt.Color(245, 245, 245));
        panelAyuda.setLayout(new java.awt.BorderLayout());

        panelCabeceraAyuda.setBackground(new java.awt.Color(255, 255, 255));

        etqTituloAyuda.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        etqTituloAyuda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etqTituloAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_ayuda_128.png"))); // NOI18N
        etqTituloAyuda.setText("Centro de Ayuda y Soporte");

        etqBuscarAyuda.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        etqBuscarAyuda.setText("Buscar en Ayuda...");
        etqBuscarAyuda.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        javax.swing.GroupLayout panelCabeceraAyudaLayout = new javax.swing.GroupLayout(panelCabeceraAyuda);
        panelCabeceraAyuda.setLayout(panelCabeceraAyudaLayout);
        panelCabeceraAyudaLayout.setHorizontalGroup(
            panelCabeceraAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraAyudaLayout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(etqTituloAyuda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addComponent(etqBuscarAyuda))
        );
        panelCabeceraAyudaLayout.setVerticalGroup(
            panelCabeceraAyudaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCabeceraAyudaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etqTituloAyuda)
                .addGap(38, 38, 38))
            .addGroup(panelCabeceraAyudaLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(etqBuscarAyuda)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAyuda.add(panelCabeceraAyuda, java.awt.BorderLayout.PAGE_START);

        jSplitPane1.setDividerLocation(250);

        jScrollPane4.setMinimumSize(new java.awt.Dimension(250, 250));

        lstAyuda.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1. Primeros Pasos", "2. Gestión de Clientes", "3. Cómo crear una Factura", "4. Control de Stock", "5. Copias de Seguridad", "6. Contactar Soporte Técnico" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstAyuda.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lstAyuda.setMinimumSize(new java.awt.Dimension(250, 0));
        jScrollPane4.setViewportView(lstAyuda);

        jSplitPane1.setLeftComponent(jScrollPane4);

        jEditorPane1.setEditable(false);
        jEditorPane1.setBackground(new java.awt.Color(255, 255, 255));
        jEditorPane1.setContentType("text/html"); // NOI18N
        jEditorPane1.setText("          <html>\n            <body style=\"font-family: sans-serif; padding: 20px;\">\n              <h1>Bienvenido a la Ayuda</h1>\n              <p>Selecciona un tema del menú de la izquierda.</p>\n            </body>\n          </html>\n");
        jScrollPane5.setViewportView(jEditorPane1);

        jSplitPane1.setRightComponent(jScrollPane5);

        panelAyuda.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        panelPrincipal.add(panelAyuda, "cardAyuda");

        getContentPane().add(panelPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardClientes");
        
        etqTitulo.setText("APP MI TALLER - CLIENTES");
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardInicio");
        
        etqTitulo.setText("APP MI TALLER - INICIO");
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btnVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVehiculosActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardVehiculos");
        
        etqTitulo.setText("APP MI TALLER - VEHÍCULOS");
    }//GEN-LAST:event_btnVehiculosActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardProveedores");
        
        etqTitulo.setText("APP MI TALLER - PROVEEDORES");
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardProductos");
        
        etqTitulo.setText("APP MI TALLER - PRODUCTOS");
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnPresupuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPresupuestosActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardPresupuestos");
        
        etqTitulo.setText("APP MI TALLER - PRESUPUESTOS");
    }//GEN-LAST:event_btnPresupuestosActionPerformed

    private void btnFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturasActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardFacturas");
        
        etqTitulo.setText("APP MI TALLER - FACTURAS");
    }//GEN-LAST:event_btnFacturasActionPerformed

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardAyuda");
        
        etqTitulo.setText("APP MI TALLER - AYUDA");
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardEmpleados");
        
        etqTitulo.setText("APP MI TALLER - EMPLEADOS");
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnReparacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReparacionesActionPerformed
        // 1. Obtener el Layout de panelPrincipal
        CardLayout cardLayout = (CardLayout) panelPrincipal.getLayout();

        // 2. Mostrar la tarjeta usando el "Card Name" que definimos
        cardLayout.show(panelPrincipal, "cardReparaciones");
        
        etqTitulo.setText("APP MI TALLER - REPARACIONES");
    }//GEN-LAST:event_btnReparacionesActionPerformed

    private void btnNuevoPresupuestosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoPresupuestosActionPerformed
        DialogPresupuesto dialogPresupuesto = new DialogPresupuesto(this, true);
        dialogPresupuesto.setVisible(true);
    }//GEN-LAST:event_btnNuevoPresupuestosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DialogNuevaReparacion nuevaReparacion = new DialogNuevaReparacion(this, true);
        nuevaReparacion.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DialogDetallesReparacion detallesReparacion = new DialogDetallesReparacion(this, true);
        detallesReparacion.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DialogHistorialCliente historialCliente = new DialogHistorialCliente(this, true);
        historialCliente.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        // Aplica el Look and Feel de Material Design
        try {
            UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new mdlaf.themes.MaterialLiteTheme()));
        } catch (javax.swing.UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    // --- FIN DEL BLOQUE ---
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarEmpleado;
    private javax.swing.JButton btnBuscarFacturas;
    private javax.swing.JButton btnBuscarPresupuestos;
    private javax.swing.JButton btnBuscarProductos;
    private javax.swing.JButton btnBuscarProveedores;
    private javax.swing.JButton btnBuscarVehiculo;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarEmpleado;
    private javax.swing.JButton btnEliminarFacturas;
    private javax.swing.JButton btnEliminarPresupuestos;
    private javax.swing.JButton btnEliminarProductos;
    private javax.swing.JButton btnEliminarProveedores;
    private javax.swing.JButton btnEliminarVehiculo;
    private javax.swing.JButton btnEmpleados;
    private javax.swing.JButton btnFacturas;
    private javax.swing.JButton btnInforme;
    private javax.swing.JButton btnInformeEmpleado;
    private javax.swing.JButton btnInformeFacturas;
    private javax.swing.JButton btnInformePresupuestos;
    private javax.swing.JButton btnInformeProductos;
    private javax.swing.JButton btnInformeProveedores;
    private javax.swing.JButton btnInformeVehiculo;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnNuevoEmpleado;
    private javax.swing.JButton btnNuevoFacturas;
    private javax.swing.JButton btnNuevoPresupuestos;
    private javax.swing.JButton btnNuevoProductos;
    private javax.swing.JButton btnNuevoProveedores;
    private javax.swing.JButton btnNuevoVehiculo;
    private javax.swing.JButton btnPresupuestos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnReparaciones;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnVehiculos;
    private javax.swing.JLabel etqBienvenida;
    private javax.swing.JLabel etqBuscarAyuda;
    private javax.swing.JLabel etqGestionEmpleados;
    private javax.swing.JLabel etqGestionFacturas;
    private javax.swing.JLabel etqGestionPresupuestos;
    private javax.swing.JLabel etqGestionProductos;
    private javax.swing.JLabel etqGestionProveedores;
    private javax.swing.JLabel etqGestionVehiculos;
    private javax.swing.JLabel etqLogo;
    private javax.swing.JLabel etqReloj;
    private javax.swing.JLabel etqTitulo;
    private javax.swing.JLabel etqTituloAyuda;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JScrollPane jScrollPaneClientes1;
    private javax.swing.JScrollPane jScrollPaneFacturas;
    private javax.swing.JScrollPane jScrollPanePresupuestos;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JScrollPane jScrollPaneProveedores;
    private javax.swing.JScrollPane jScrollPaneVehiculos;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JList<String> lstAyuda;
    private javax.swing.JPanel panelAgenda;
    private javax.swing.JPanel panelAyuda;
    private javax.swing.JPanel panelBarraHerramientas;
    private javax.swing.JPanel panelBienvenida;
    private javax.swing.JPanel panelCabeceraAyuda;
    private javax.swing.JPanel panelClientes;
    private javax.swing.JPanel panelCuerpo;
    private javax.swing.JPanel panelEmpleados;
    private javax.swing.JPanel panelEstadoTaller;
    private javax.swing.JPanel panelFacturas;
    private javax.swing.JPanel panelHerramientas;
    private javax.swing.JPanel panelHerramientasEmpleados;
    private javax.swing.JPanel panelHerramientasFacturas;
    private javax.swing.JPanel panelHerramientasPresupuestos;
    private javax.swing.JPanel panelHerramientasProductos;
    private javax.swing.JPanel panelHerramientasProveedores;
    private javax.swing.JPanel panelHerramientasVehiculos;
    private javax.swing.JPanel panelIndicadores;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel panelNavegacion;
    private javax.swing.JPanel panelPresupuestos;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelProductos;
    private javax.swing.JPanel panelProveedores;
    private javax.swing.JPanel panelReparaciones;
    private javax.swing.JPanel panelStock;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel panelVehiculos;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTable tblClientes1;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JTable tblPresupuestos;
    private javax.swing.JTable tblProductos;
    private javax.swing.JTable tblProveedores;
    private javax.swing.JTable tblVehiculo;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtBuscarEmpleado;
    private javax.swing.JTextField txtBuscarFacturas;
    private javax.swing.JTextField txtBuscarPresupuestos;
    private javax.swing.JTextField txtBuscarProductos;
    private javax.swing.JTextField txtBuscarProveedores;
    private javax.swing.JTextField txtBuscarVehiculo;
    // End of variables declaration//GEN-END:variables

    private void iniciarReloj() {
        // Actualiza cada 1000ms (1 segundo)
    new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            java.text.SimpleDateFormat formato = new java.text.SimpleDateFormat("dd 'de' MMMM 'de' yyyy - HH:mm:ss");
            String fecha = formato.format(new java.util.Date());
            // Pon aquí el nombre de TU variable (lblReloj, jLabel2, etc.)
            etqReloj.setText(fecha.toUpperCase()); 
        }
    }).start();
    }
}
