
package com.joseluis.apptaller.vista.dialogos;

import com.joseluis.apptaller.logica.GestorFacturacion;
import com.joseluis.apptaller.modelo.dao.FacturaDAO;
import com.joseluis.apptaller.modelo.dao.PresupuestoDAO;
import javax.swing.UIManager;
import com.joseluis.apptaller.modelo.vo.ClienteVO;
import com.joseluis.apptaller.modelo.vo.VehiculoVO;
import com.joseluis.apptaller.modelo.dao.VehiculoDAO;
import com.joseluis.apptaller.modelo.vo.FacturaVO;
import com.joseluis.apptaller.modelo.vo.PresupuestoVO;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana de diálogo que muestra el historial completo de un cliente.
 * Agrupa su información personal básica y organiza en pestañas todos los 
 * vehículos, presupuestos y facturas asociadas a su perfil, ofreciendo 
 * una vista panorámica de su actividad y relación con el taller.
 *
 * @author José Luis Cárdenas Barroso
 * @info Proyecto Intermodular del Grado Superior DAM
 * @institution IES Augustóbriga
 */
public class DialogHistorialCliente extends JDialog {
    // Añadimos la variable para guardar el cliente
    private ClienteVO cliente;

    /**
     * Creates new form DialogHistorialCliente
     */
    public DialogHistorialCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }
    
    // Creamos un constructor sobrecargado que reciba al cliente
    public DialogHistorialCliente(java.awt.Frame parent, boolean modal, ClienteVO cliente) {
        super(parent, modal);
        this.cliente = cliente; // Guardamos el cliente
        initComponents();
        setLocationRelativeTo(this);
        
        // Llamamos a los métodos que rellenan los datos
        cargarDatosPersonales();
        cargarVehiculos();
        cargarPresupuestos(cliente.getDni());
        cargarFacturas(cliente.getDni());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDatosCliente = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblTlf = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jTabbedPaneCentral = new javax.swing.JTabbedPane();
        panelVehiculos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculosCliente = new javax.swing.JTable();
        panelPresupuestos = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPresupuestos = new javax.swing.JTable();
        panelFacturas = new javax.swing.JPanel();
        panelBotonFacturas = new javax.swing.JPanel();
        btnImprimirFactura = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFacturas = new javax.swing.JTable();
        panelInferior = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha Histórica del Cliente");
        setModal(true);

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_apptaller_small.png"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        lblDni.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblDni.setText("DNI: ");

        lblTlf.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTlf.setText("Teléfono: ");

        lblMail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblMail.setText("Email: ");

        lblDNI.setText("jLabel1");

        lblTelefono.setText("jLabel1");

        lblEmail.setText("jLabel1");

        javax.swing.GroupLayout panelDatosClienteLayout = new javax.swing.GroupLayout(panelDatosCliente);
        panelDatosCliente.setLayout(panelDatosClienteLayout);
        panelDatosClienteLayout.setHorizontalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono)
                .addGap(76, 76, 76)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDni)
                            .addComponent(lblTlf)
                            .addComponent(lblMail))
                        .addGap(30, 30, 30)
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblTelefono)
                            .addComponent(lblDNI))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        panelDatosClienteLayout.setVerticalGroup(
            panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosClienteLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIcono)
                    .addGroup(panelDatosClienteLayout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDni)
                            .addComponent(lblDNI))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTlf)
                            .addComponent(lblTelefono))
                        .addGap(18, 18, 18)
                        .addGroup(panelDatosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMail)
                            .addComponent(lblEmail))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelDatosCliente, java.awt.BorderLayout.PAGE_START);

        panelVehiculos.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        tablaVehiculosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1234-BBB", "Ford", "Fiesta", "2015", "13/08/2024"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Marca", "Modelo", "Año", "Última visita"
            }
        ));
        jScrollPane1.setViewportView(tablaVehiculosCliente);

        panelVehiculos.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPaneCentral.addTab("Vehículos", panelVehiculos);

        panelPresupuestos.setLayout(new java.awt.BorderLayout());

        tblPresupuestos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nº Presupuesto", "Fecha", "Vehículo", "Total", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tblPresupuestos);

        panelPresupuestos.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPaneCentral.addTab("Presupuestos", panelPresupuestos);

        panelFacturas.setLayout(new java.awt.BorderLayout());

        btnImprimirFactura.setText("Imprimir PDF");
        btnImprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBotonFacturasLayout = new javax.swing.GroupLayout(panelBotonFacturas);
        panelBotonFacturas.setLayout(panelBotonFacturasLayout);
        panelBotonFacturasLayout.setHorizontalGroup(
            panelBotonFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonFacturasLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(btnImprimirFactura)
                .addContainerGap(330, Short.MAX_VALUE))
        );
        panelBotonFacturasLayout.setVerticalGroup(
            panelBotonFacturasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonFacturasLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnImprimirFactura)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panelFacturas.add(panelBotonFacturas, java.awt.BorderLayout.PAGE_START);

        tblFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº Factura", "Fecha", "Base Imponible", "IVA", "Total", "Estado"
            }
        ));
        jScrollPane3.setViewportView(tblFacturas);

        panelFacturas.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPaneCentral.addTab("Facturas", panelFacturas);

        getContentPane().add(jTabbedPaneCentral, java.awt.BorderLayout.CENTER);

        panelInferior.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCerrar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        panelInferior.add(btnCerrar);

        getContentPane().add(panelInferior, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose(); // Cierra el JDialog liberando memoria
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnImprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirFacturaActionPerformed
        int fila = tblFacturas.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione una factura del historial para imprimirla.");
            return;
        }

        try {
            String numeroFactura = tblFacturas.getValueAt(fila, 0).toString();
           
            GestorFacturacion gestor = new GestorFacturacion();
            gestor.visualizarFacturaGenerica(numeroFactura);
           
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al imprimir la factura: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnImprimirFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        // Aplica el Look and Feel de Material Design
        try {
            UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new mdlaf.themes.MaterialOceanicTheme()));
        } catch (javax.swing.UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    // --- FIN DEL BLOQUE ---
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogHistorialCliente dialog = new DialogHistorialCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnImprimirFactura;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPaneCentral;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTlf;
    private javax.swing.JPanel panelBotonFacturas;
    private javax.swing.JPanel panelDatosCliente;
    private javax.swing.JPanel panelFacturas;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelPresupuestos;
    private javax.swing.JPanel panelVehiculos;
    private javax.swing.JTable tablaVehiculosCliente;
    private javax.swing.JTable tblFacturas;
    private javax.swing.JTable tblPresupuestos;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosPersonales() {
        // Sustituimos los textos por defecto por los del cliente real
        lblNombre.setText(cliente.getNombre().toUpperCase());
        lblDNI.setText(cliente.getDni());
        lblTelefono.setText(cliente.getTelefono());
        lblEmail.setText(cliente.getEmail());
    }
    

    private void cargarVehiculos() {
        // Usamos el VehiculoDAO que ya tengo creado para buscar los coches de este DNI
        VehiculoDAO vehiculoDAO = new VehiculoDAO();
        List<VehiculoVO> vehiculos = vehiculoDAO.listarPorCliente(cliente.getDni());
        
        // Accedemos al modelo del jTable (la de vehículos)
        DefaultTableModel modelo = (DefaultTableModel) tablaVehiculosCliente.getModel();
        modelo.setRowCount(0); // Limpiamos las filas de prueba

        // Rellenamos con datos reales
        for (VehiculoVO v : vehiculos) {
            Object[] fila = new Object[5];
            fila[0] = v.getMatricula();
            fila[1] = v.getMarca();
            fila[2] = v.getModelo();
            fila[3] = v.getAnioFabricacion();
            fila[4] = "Pendiente..."; // La última visita la calcularemos en la Fase de Reparaciones
            modelo.addRow(fila);
        }
    }
    
    
    private void cargarPresupuestos(String dniCliente) {
        DefaultTableModel modelo = (DefaultTableModel) tblPresupuestos.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        PresupuestoDAO pDAO = new PresupuestoDAO();
        List<PresupuestoVO> lista = pDAO.listarPorCliente(dniCliente);

        for (PresupuestoVO p : lista) {
            modelo.addRow(new Object[]{
                p.getIdPresupuesto(),
                p.getFechaEmision(),
                p.getMatriculaVehiculo(),
                String.format("%.2f€", p.getTotalEstimado()),
                p.getEstado()
            });
        }
    }
    
    private void cargarFacturas(String dniCliente) {
        DefaultTableModel modelo = (DefaultTableModel) tblFacturas.getModel();
        modelo.setRowCount(0);

        FacturaDAO fDAO = new FacturaDAO();
        List<FacturaVO> lista = fDAO.listarPorCliente(dniCliente);

        for (FacturaVO f : lista) {
            modelo.addRow(new Object[]{
                f.getNumeroFactura(),
                f.getFechaEmision(),
                String.format("%.2f €", f.getBaseImponible()),
                String.format("%.2f €", f.getIva()), 
                String.format("%.2f€", f.getTotalCobrado()),
                f.getEstado()
            });
        }
    }
}
