
package com.joseluis.apptaller.vista.dialogos;

import com.joseluis.apptaller.modelo.vo.ClienteVO;
import com.joseluis.apptaller.modelo.vo.EmpleadoVO;
import java.time.LocalDate;
import javax.swing.JOptionPane;

/**
 *
 * @author joseluis
 */
public class DialogNuevoEmpleado extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogNuevoEmpleado.class.getName());
    
    private EmpleadoVO empleado;
    private boolean guardado;
    
    // Variables para "recordar" datos internos al editar
    private LocalDate fechaAltaOriginal;
    private LocalDate fechaBajaOriginal;
    private int idEmpleadoOriginal = 0;
    private int usuarioIdOriginal = 0; // 
    
    // --- CONSTRUCTOR 1: PARA ALTA NUEVA ---
    public DialogNuevoEmpleado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        setTitle("Nuevo Empleado");
        this.guardado = false;
       
        btnGuardar.addActionListener(e -> guardar());
        btnCancelar.addActionListener(e -> cancelar());
        this.getRootPane().setDefaultButton(btnGuardar);
    }
    
     // --- CONSTRUCTOR 2: PARA EDICIÓN ---
    public DialogNuevoEmpleado(java.awt.Frame parent, boolean modal, EmpleadoVO empleadoAEditar) {
        this(parent, modal);
        setTitle("Editar Empleado");
       
        // Guardamos los IDs internos para no perderlos
        this.idEmpleadoOriginal = empleadoAEditar.getId_empleado();
        this.usuarioIdOriginal = empleadoAEditar.getUsuario_id();
        this.fechaAltaOriginal = empleadoAEditar.getFecha_alta();
        this.fechaBajaOriginal = empleadoAEditar.getFecha_baja();
       
        // Rellenamos los campos de texto
        txtDni.setText(empleadoAEditar.getDni());
        txtDni.setEditable(false); // Seguimos bloqueando el DNI por seguridad
        txtNombre.setText(empleadoAEditar.getNombre());
        txtApellidos.setText(empleadoAEditar.getApellidos());
        txtTelefono.setText(empleadoAEditar.getTelefono());
        txtEmail.setText(empleadoAEditar.getEmail());
        txtDireccion.setText(empleadoAEditar.getDireccion());
        txtSalario.setText(String.valueOf(empleadoAEditar.getSalario_base()));
        cbxCargo.setSelectedItem(empleadoAEditar.getCargo());
    }
    
     // --- LÓGICA DE GUARDAR ---
    private void guardar() {
        if (txtDni.getText().trim().isEmpty() || txtNombre.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El DNI y el Nombre son obligatorios.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        float salarioMeteUsuario = 0;
        try {
            String textoSalario = txtSalario.getText().trim().replace(",", ".");
            if (!textoSalario.isEmpty()) {
                salarioMeteUsuario = Float.parseFloat(textoSalario);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El salario debe ser un número válido.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Empaquetar el EmpleadoVO con TODOS sus campos
        empleado = new EmpleadoVO();
       
        // Restauramos los IDs internos
        empleado.setId_empleado(idEmpleadoOriginal);
        empleado.setUsuario_id(usuarioIdOriginal);
       
        empleado.setDni(txtDni.getText().trim().toUpperCase());
        empleado.setNombre(txtNombre.getText().trim());
        empleado.setApellidos(txtApellidos.getText().trim());
        empleado.setTelefono(txtTelefono.getText().trim());
        empleado.setEmail(txtEmail.getText().trim());
        empleado.setDireccion(txtDireccion.getText().trim());
        empleado.setCargo((String) cbxCargo.getSelectedItem());
        empleado.setSalario_base(salarioMeteUsuario);
       
        if (fechaAltaOriginal != null) {
            empleado.setFecha_alta(fechaAltaOriginal);
        } else {
            empleado.setFecha_alta(LocalDate.now());
        }
        empleado.setFecha_baja(fechaBajaOriginal);

        this.guardado = true;
        this.dispose();
    }
    
     private void cancelar() {
        this.guardado = false;
        this.dispose();
    }
     
    public boolean isGuardado() { return guardado; }
    public EmpleadoVO getEmpleado() { return empleado; }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblDNI = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        pnlLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        lblCargo = new javax.swing.JLabel();
        lblSalario = new javax.swing.JLabel();
        txtSalario = new javax.swing.JTextField();
        cbxCargo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta / Modificación Cliente");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(445, 660));

        lblDNI.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblDNI.setText("DNI");

        txtDni.setColumns(20);
        txtDni.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        lblNombre.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblNombre.setText("Nombre");

        txtNombre.setColumns(20);
        txtNombre.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        lblTelefono.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblTelefono.setText("Teléfono");

        txtTelefono.setColumns(20);
        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        lblEmail.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setColumns(20);
        txtEmail.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        lblDireccion.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblDireccion.setText("Dirección");

        txtDireccion.setColumns(20);
        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnCancelar.setText("Cancelar");

        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnGuardar.setText("Guardar");

        pnlTitulo.setBackground(new java.awt.Color(33, 150, 243));

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("ALTA / MODIFICACIÓN DE EMPLEADOS");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap())
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(30, 30, 30))
        );

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_apptaller_titulo.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLogo)
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
        );

        lblApellidos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblApellidos.setText("Apellidos");

        txtApellidos.setColumns(20);
        txtApellidos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        lblCargo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblCargo.setText("Cargo");

        lblSalario.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblSalario.setText("Salario Base");

        txtSalario.setColumns(20);
        txtSalario.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        cbxCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jefe de Taller", "Mecánico", "Administración", "Recepcionista" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(btnCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnGuardar)
                                .addGap(81, 81, 81))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSalario)
                                        .addGap(42, 42, 42)
                                        .addComponent(txtSalario))
                                    .addComponent(lblApellidos)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblTelefono)
                                            .addComponent(lblDireccion)
                                            .addComponent(lblNombre)
                                            .addComponent(lblDNI)
                                            .addComponent(lblEmail)
                                            .addComponent(lblCargo))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtNombre)
                                            .addComponent(txtDni)
                                            .addComponent(txtApellidos)
                                            .addComponent(txtTelefono)
                                            .addComponent(txtEmail)
                                            .addComponent(txtDireccion)
                                            .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDNI))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellidos)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDireccion)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCargo)
                    .addComponent(cbxCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSalario)
                    .addComponent(txtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxCargo;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCargo;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSalario;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

}