
package com.joseluis.apptaller.vista.dialogos;


import com.joseluis.apptaller.logica.GestorFacturacion;
import com.joseluis.apptaller.modelo.vo.FacturaVO;
import javax.swing.JOptionPane;

/**
 * Ventana de diálogo encargada de la emisión y registro de nuevas facturas.
 * Muestra el resumen económico de una reparación finalizada, permite seleccionar 
 * el método de pago y delega el guardado en base de datos y la generación del PDF 
 * al gestor de facturación correspondiente.
 *
 * @author José Luis Cárdenas Barroso
 * @info Proyecto Intermodular del Grado Superior DAM
 * @institution IES Augustóbriga
 */
public class DialogGenerarFactura extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogGenerarFactura.class.getName());

    private GestorFacturacion gestorFacturacion;
    private FacturaVO facturaEnProceso;
       

    
    public DialogGenerarFactura(java.awt.Frame parent, boolean modal, int idReparacion, 
                            int idPresupuesto, String clienteDni, String bastidor, 
                            double totalManoObra, double totalProductos) {
        super(parent, modal);
        initComponents();

        // Inyectamos la lógica
        this.gestorFacturacion = new GestorFacturacion();
        this.setLocationRelativeTo(parent);

        // Preparamos los datos iniciales
        prepararDatos(idReparacion, idPresupuesto, clienteDni, bastidor, totalManoObra, totalProductos);
}
  
    
    private void prepararDatos(int idReparacion, int idPresupuesto, String clienteDni, String bastidor, double mo, double prod) {
        // El gestor realiza los cálculos de IVA y totales
        this.facturaEnProceso = gestorFacturacion.prepararFacturaDesdeReparacion(
                idReparacion, idPresupuesto, clienteDni, bastidor, mo, prod);

        // Volcamos a la UI
        txtNumeroFactura.setText(facturaEnProceso.getNumeroFactura());
        txtFechaEmision.setText(facturaEnProceso.getFechaEmision().toString());
        txtBaseImponible.setText(String.format("%.2f", facturaEnProceso.getBaseImponible()));
        txtIva.setText(String.format("%.2f", (facturaEnProceso.getBaseImponible() * 0.21)));
        txtTotalCobrado.setText(String.format("%.2f", facturaEnProceso.getTotalCobrado()));
    }
    
    
    /**
     * Creates new form DialogGenerarFactura
     */
    public DialogGenerarFactura(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        panelTitulo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        panelContenido = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        lblNumeroFactura = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFechaEmision = new javax.swing.JTextField();
        panelResumen = new javax.swing.JPanel();
        lblBase = new javax.swing.JLabel();
        txtBaseImponible = new javax.swing.JTextField();
        lblIva = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtTotalCobrado = new javax.swing.JTextField();
        panelDetallesCobro = new javax.swing.JPanel();
        lblMetodoPago = new javax.swing.JLabel();
        cbxMetodoPago = new javax.swing.JComboBox<>();
        lblObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaObservaciones = new javax.swing.JTextArea();
        panelInferiror = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emitir Nueva Factura");
        setModal(true);

        panelTitulo.setBackground(new java.awt.Color(33, 150, 243));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_apptaller_small.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("NUEVA FACTURA");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118)
                .addComponent(lblTitulo)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(51, 51, 51))
        );

        panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos Generales"));

        lblNumeroFactura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblNumeroFactura.setText("Nº Factura");

        txtNumeroFactura.setEditable(false);
        txtNumeroFactura.setColumns(10);
        txtNumeroFactura.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblFecha.setText("Fecha de Emisión:");

        txtFechaEmision.setEditable(false);
        txtFechaEmision.setColumns(10);
        txtFechaEmision.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblNumeroFactura)
                .addGap(18, 18, 18)
                .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lblFecha)
                .addGap(18, 18, 18)
                .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroFactura)
                    .addComponent(txtNumeroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFecha)
                    .addComponent(txtFechaEmision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        panelContenido.add(panelDatos);

        panelResumen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Resumen Económico"));

        lblBase.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblBase.setText("Base Imponible");

        txtBaseImponible.setEditable(false);
        txtBaseImponible.setColumns(10);
        txtBaseImponible.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBaseImponible.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblIva.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblIva.setText("IVA (21%):");

        txtIva.setEditable(false);
        txtIva.setColumns(10);
        txtIva.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel1.setText("TOTAL A COBRAR (€)");

        txtTotalCobrado.setEditable(false);
        txtTotalCobrado.setColumns(10);
        txtTotalCobrado.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        txtTotalCobrado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout panelResumenLayout = new javax.swing.GroupLayout(panelResumen);
        panelResumen.setLayout(panelResumenLayout);
        panelResumenLayout.setHorizontalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBase)
                    .addComponent(lblIva)
                    .addComponent(jLabel1))
                .addGap(32, 32, 32)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotalCobrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBaseImponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        panelResumenLayout.setVerticalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBase)
                    .addComponent(txtBaseImponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIva)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCobrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        panelContenido.add(panelResumen);

        panelDetallesCobro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Detalles de Cobro"));

        lblMetodoPago.setText("Método de Pago");

        cbxMetodoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta", "Transferencia", "Financiación", "Mixto" }));

        lblObservaciones.setText("Observaciones");

        txaObservaciones.setColumns(20);
        txaObservaciones.setRows(5);
        jScrollPane1.setViewportView(txaObservaciones);

        javax.swing.GroupLayout panelDetallesCobroLayout = new javax.swing.GroupLayout(panelDetallesCobro);
        panelDetallesCobro.setLayout(panelDetallesCobroLayout);
        panelDetallesCobroLayout.setHorizontalGroup(
            panelDetallesCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDetallesCobroLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panelDetallesCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblObservaciones)
                    .addGroup(panelDetallesCobroLayout.createSequentialGroup()
                        .addComponent(lblMetodoPago)
                        .addGap(36, 36, 36)
                        .addComponent(cbxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDetallesCobroLayout.setVerticalGroup(
            panelDetallesCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDetallesCobroLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelDetallesCobroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMetodoPago)
                    .addComponent(cbxMetodoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(lblObservaciones)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelContenido.add(panelDetallesCobro);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        btnGenerar.setBackground(new java.awt.Color(33, 150, 243));
        btnGenerar.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerar.setText("Generar y Guardar Factura");
        btnGenerar.addActionListener(this::btnGenerarActionPerformed);

        javax.swing.GroupLayout panelInferirorLayout = new javax.swing.GroupLayout(panelInferiror);
        panelInferiror.setLayout(panelInferirorLayout);
        panelInferirorLayout.setHorizontalGroup(
            panelInferirorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferirorLayout.createSequentialGroup()
                .addContainerGap(153, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(107, 107, 107)
                .addComponent(btnGenerar)
                .addGap(151, 151, 151))
        );
        panelInferirorLayout.setVerticalGroup(
            panelInferirorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferirorLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addGroup(panelInferirorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGenerar))
                .addGap(29, 29, 29))
        );

        panelContenido.add(panelInferiror);

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(panelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(panelContenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose(); // Cierra el modal sin hacer nada
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        try {
            // Validamos selección de método de pago
            String metodo = cbxMetodoPago.getSelectedItem().toString();
            facturaEnProceso.setMetodoPago(metodo);
            facturaEnProceso.setObservaciones(txaObservaciones.getText());

            facturaEnProceso.setUsuarioEmisor(1); 

            // Guardamos en Base de Datos
            boolean exito = gestorFacturacion.registrarNuevaFactura(facturaEnProceso);

            if (exito) {
                JOptionPane.showMessageDialog(this, "Factura generada y registrada con éxito.", 
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);

                // Preguntamos si desea imprimir el PDF 
                int respuesta = JOptionPane.showConfirmDialog(this, "¿Desea visualizar/imprimir la factura en PDF?", 
                        "Imprimir", JOptionPane.YES_NO_OPTION);

                if (respuesta == JOptionPane.YES_OPTION) {
                    // Obtenemos las líneas reales de la reparación
                    java.util.List<com.joseluis.apptaller.modelo.vo.DetalleFactura> lineasDetalle = 
                        gestorFacturacion.obtenerDetallesParaFactura(facturaEnProceso.getIdReparacion());

                    // Imprimimos el PDF con datos
                    gestorFacturacion.generarInformePDF(facturaEnProceso, lineasDetalle);
                }

                this.dispose(); // Cerramos el dialog
            } else {
                JOptionPane.showMessageDialog(this, "Error al guardar la factura en la base de datos.", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error crítico: " + e.getMessage());
        }
        
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogGenerarFactura dialog = new DialogGenerarFactura(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JComboBox<String> cbxMetodoPago;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblMetodoPago;
    private javax.swing.JLabel lblNumeroFactura;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelDetallesCobro;
    private javax.swing.JPanel panelInferiror;
    private javax.swing.JPanel panelResumen;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextArea txaObservaciones;
    private javax.swing.JTextField txtBaseImponible;
    private javax.swing.JTextField txtFechaEmision;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtTotalCobrado;
    // End of variables declaration//GEN-END:variables
}
