
package com.joseluis.apptaller.vista.dialogos;

import com.joseluis.apptaller.modelo.vo.VehiculoVO;
import com.joseluis.apptaller.modelo.vo.ClienteVO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author joseluis
 */
public class DialogNuevoVehiculo extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogNuevoVehiculo.class.getName());
    
    private VehiculoVO vehiculo;
    private boolean guardado;

    /**
     * Creates new form DialogNuevoVehiculo
     */
    public DialogNuevoVehiculo(java.awt.Frame parent, boolean modal, List<ClienteVO>clientesActivos) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(parent);
        this.guardado = false;
        
        cargarClientesEnCombo(clientesActivos);
        
        // Listeners
        btnGuardar.addActionListener(e -> guardar());
        btnCancelar.addActionListener(e -> cancelar());
        
        // UX: Botón por defecto al pulsar Intro
        this.getRootPane().setDefaultButton(btnGuardar);
        
    }
    
    // Constructor sobrecargado para EDITAR un vehículo existente
    public DialogNuevoVehiculo(java.awt.Frame parent, boolean modal, java.util.List<ClienteVO>clientesActivos, VehiculoVO vehiculoAEditar) {
        this(parent, modal, clientesActivos); // Llama al constructor por defecto que inicializa todo
        setTitle("Editar Vehículo");
        
        // 1. Volcamos los datos en los campos de texto
        txtBastidor.setText(vehiculoAEditar.getBastidor());
        txtBastidor.setEditable(false); // BLOQUEAMOS la clave primaria para que no la rompan
        txtMatricula.setText(vehiculoAEditar.getMatricula());
        txtMarca.setText(vehiculoAEditar.getMarca());
        txtModelo.setText(vehiculoAEditar.getModelo());
        txtColor.setText(vehiculoAEditar.getColor());
        txtAnio.setText(String.valueOf(vehiculoAEditar.getAnioFabricacion()));
        
        // 2. Buscamos y seleccionamos al dueño correcto en el desplegable (JComboBox)
        String dniDueño = vehiculoAEditar.getDniPropietario();
        for (int i = 0; i < cbxClientes.getItemCount(); i++) {
            String item = (String) cbxClientes.getItemAt(i);
            if (item.startsWith(dniDueño + " -")) { // Si el item empieza por el DNI del dueño
                cbxClientes.setSelectedIndex(i);
                break;
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBastidor = new javax.swing.JLabel();
        txtBastidor = new javax.swing.JTextField();
        lblMatricula = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        lblMarca = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        lblModelo = new javax.swing.JLabel();
        txtModelo = new javax.swing.JTextField();
        lblAnio = new javax.swing.JLabel();
        txtAnio = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cbxClientes = new javax.swing.JComboBox<>();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        pnlLogo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alta Nuevo Vehículo");
        setModal(true);

        lblBastidor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblBastidor.setText("Bastidor");

        txtBastidor.setColumns(15);
        txtBastidor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lblMatricula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblMatricula.setText("Matrícula");

        txtMatricula.setColumns(15);
        txtMatricula.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lblMarca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblMarca.setText("Marca");

        txtMarca.setColumns(15);
        txtMarca.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lblModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblModelo.setText("Modelo");

        txtModelo.setColumns(15);
        txtModelo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lblAnio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblAnio.setText("Año");

        txtAnio.setColumns(15);
        txtAnio.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lblColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblColor.setText("Color");

        txtColor.setColumns(15);
        txtColor.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel1.setText("Propietario");

        cbxClientes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbxClientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCancelar.setText("Cancelar");

        btnGuardar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnGuardar.setText("Guardar");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_apptaller_titulo.png"))); // NOI18N

        javax.swing.GroupLayout pnlLogoLayout = new javax.swing.GroupLayout(pnlLogo);
        pnlLogo.setLayout(pnlLogoLayout);
        pnlLogoLayout.setHorizontalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );
        pnlLogoLayout.setVerticalGroup(
            pnlLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
        );

        pnlTitulo.setBackground(new java.awt.Color(33, 150, 243));

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("ALTA / MODIFICACIÓN DE VEHÍCULOS");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTituloLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBastidor)
                            .addComponent(lblMatricula)
                            .addComponent(lblMarca)
                            .addComponent(lblModelo)
                            .addComponent(lblAnio)
                            .addComponent(lblColor)
                            .addComponent(jLabel1))
                        .addGap(95, 95, 95)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMatricula)
                            .addComponent(txtBastidor)
                            .addComponent(txtMarca)
                            .addComponent(txtModelo)
                            .addComponent(txtAnio)
                            .addComponent(txtColor)
                            .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnCancelar)
                        .addGap(82, 82, 82)
                        .addComponent(btnGuardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(pnlLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBastidor)
                    .addComponent(txtBastidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMarca)
                    .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModelo)
                    .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnio)
                    .addComponent(txtAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbxClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogNuevoVehiculo dialog = new DialogNuevoVehiculo(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblBastidor;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlLogo;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtBastidor;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables

    private void cargarClientesEnCombo(List<ClienteVO> clientes) {
        cbxClientes.removeAllItems();
        if (clientes.isEmpty()) {
            cbxClientes.addItem("No hay clientes registrados");
            btnGuardar.setEnabled(false); // Evitamos que guarde si no hay clientes
            return;
            }
        for (ClienteVO c : clientes) {
        // Guardamos DNI y Nombre separados por un guion
        cbxClientes.addItem(c.getDni() + " - " + c.getNombre());
}
    }

    private void guardar() {
        // 1. Validaciones básicas
        if (txtMatricula.getText().trim().isEmpty() || txtBastidor.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "La Matrícula y el Bastidor son obligatorios.", 
                    "Aviso", JOptionPane.WARNING_MESSAGE);
        return;
        }
        
        // 2. Extraer el DNI del JComboBox (cortamos la cadena por el " - " y cogemos la primera parte
        String clienteSeleccionado = (String) cbxClientes.getSelectedItem();
        String dniPropietario = clienteSeleccionado.split(" - ")[0];
        
        // 3. Empaquetar el VehiculoVO
        vehiculo = new VehiculoVO();
        vehiculo.setBastidor(txtBastidor.getText().trim());
        vehiculo.setMatricula(txtMatricula.getText().trim().toUpperCase()); // Matrículas siempre en mayúsculas
        vehiculo.setMarca(txtMarca.getText().trim());
        vehiculo.setModelo(txtModelo.getText().trim());
        vehiculo.setColor(txtColor.getText().trim());
        vehiculo.setAnioFabricacion(Integer.parseInt(txtAnio.getText().trim()));
        vehiculo.setDniPropietario(dniPropietario);
        
        // 4. Cerramos
        this.guardado = true;
        this.dispose();
    }

    private void cancelar() {
        this.guardado = false;
        this.dispose();    
    }
    
    // Getters para el controlador
    public boolean isGuardado() { 
        return guardado; 
    }
    
    public VehiculoVO getVehiculo() {
        return vehiculo; 
    }
    
}
