
package com.joseluis.apptaller.vista.dialogos;

import javax.swing.UIManager;
import com.joseluis.apptaller.modelo.vo.ClienteVO;
import com.joseluis.apptaller.modelo.vo.VehiculoVO;
import com.joseluis.apptaller.modelo.dao.VehiculoDAO;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 * Ventana de diálogo que muestra el historial completo de un cliente.
 * Agrupa su información personal básica y organiza en pestañas todos los 
 * vehículos, presupuestos y facturas asociadas a su perfil, ofreciendo 
 * una vista panorámica de su actividad y relación con el taller.
 *
 * @author José Luis Cárdenas Barroso
 * @info Proyecto Intermodular del Grado Superior DAM
 * @institution IES Augustóbriga
 */
public class DialogHistorialCliente extends javax.swing.JDialog {
    // Añadimos la variable para guardar el cliente
    private ClienteVO cliente;

    /**
     * Creates new form DialogHistorialCliente
     */
    public DialogHistorialCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(this);
    }
    
    // Creamos un constructor sobrecargado que reciba al cliente
    public DialogHistorialCliente(java.awt.Frame parent, boolean modal, com.joseluis.apptaller.modelo.vo.ClienteVO cliente) {
        super(parent, modal);
        this.cliente = cliente; // Guardamos el cliente
        initComponents();
        setLocationRelativeTo(this);
        
        // Llamamos a los métodos que rellenan los datos
        cargarDatosPersonales();
        cargarVehiculos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblIcono = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblTlf = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblDNI = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVehiculosCliente = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ficha Histórica del Cliente");
        setModal(true);

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icono_cliente_128.png"))); // NOI18N

        lblNombre.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N

        lblDni.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblDni.setText("DNI: ");

        lblTlf.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblTlf.setText("Teléfono: ");

        lblMail.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblMail.setText("Email: ");

        lblDNI.setText("jLabel1");

        lblTelefono.setText("jLabel1");

        lblEmail.setText("jLabel1");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIcono)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNombre)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDni)
                            .addComponent(lblTlf)
                            .addComponent(lblMail))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(lblTelefono)
                            .addComponent(lblDNI))))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIcono)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblNombre)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDni)
                            .addComponent(lblDNI))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTlf)
                            .addComponent(lblTelefono))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMail)
                            .addComponent(lblEmail))))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        tablaVehiculosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1234-BBB", "Ford", "Fiesta", "2015", "13/08/2024"},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Matrícula", "Marca", "Modelo", "Año", "Última visita"
            }
        ));
        jScrollPane1.setViewportView(tablaVehiculosCliente);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Vehículos", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Ver Detalle");

        jButton4.setText("Convertir a Factura");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jButton3)
                .addGap(132, 132, 132)
                .addComponent(jButton4)
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nº Presupuesto", "Fecha", "Vehículo", "Total", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Presupuestos", jPanel4);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jButton7.setText("Imprimir PDF");

        jButton8.setText("Marcar como Pagada");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jButton7)
                .addGap(76, 76, 76)
                .addComponent(jButton8)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nº Factura", "Fecha", "Base Imponible", "IVA", "Total", "Estado"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel1.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Facturas", jPanel1);

        getContentPane().add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        jButton6.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jButton6.setText("Cerrar");
        jPanel7.add(jButton6);

        getContentPane().add(jPanel7, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        // Aplica el Look and Feel de Material Design
        try {
            UIManager.setLookAndFeel(new mdlaf.MaterialLookAndFeel(new mdlaf.themes.MaterialOceanicTheme()));
        } catch (javax.swing.UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }
    // --- FIN DEL BLOQUE ---
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogHistorialCliente dialog = new DialogHistorialCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JLabel lblDNI;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTlf;
    private javax.swing.JTable tablaVehiculosCliente;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosPersonales() {
        // Sustituimos los textos por defecto por los del cliente real
        lblNombre.setText(cliente.getNombre().toUpperCase());
        lblDNI.setText(cliente.getDni());
        lblTelefono.setText(cliente.getTelefono());
        lblEmail.setText(cliente.getEmail());
    }
    

    private void cargarVehiculos() {
        // Usamos el VehiculoDAO que ya tengo creado para buscar los coches de este DNI
        VehiculoDAO vehiculoDAO = new VehiculoDAO();
        List<VehiculoVO> vehiculos = vehiculoDAO.listarPorCliente(cliente.getDni());
        
        // Accedemos al modelo del jTable (la de vehículos)
        DefaultTableModel modelo = (DefaultTableModel) tablaVehiculosCliente.getModel();
        modelo.setRowCount(0); // Limpiamos las filas de prueba

        // Rellenamos con datos reales
        for (com.joseluis.apptaller.modelo.vo.VehiculoVO v : vehiculos) {
            Object[] fila = new Object[5];
            fila[0] = v.getMatricula();
            fila[1] = v.getMarca();
            fila[2] = v.getModelo();
            fila[3] = v.getAnioFabricacion();
            fila[4] = "Pendiente..."; // La última visita la calcularemos en la Fase de Reparaciones
            modelo.addRow(fila);
        }
    }
}
