
package com.joseluis.apptaller.vista.dialogos;

import com.joseluis.apptaller.controlador.ControladorPresupuestos;
import com.joseluis.apptaller.modelo.dao.PresupuestoDAO;
import com.joseluis.apptaller.modelo.vo.DetalleManoObraVO;
import com.joseluis.apptaller.modelo.vo.DetalleProductoVO;
import com.joseluis.apptaller.modelo.vo.PresupuestoVO;
import java.util.List;

/**
 * Ventana de diálogo que muestra la información detallada de un presupuesto existente.
 * Carga los datos generales, las piezas y la mano de obra desde la base de datos, 
 * presentándolos en modo de solo lectura para su consulta sin riesgo de modificaciones.
 *
 * @author José Luis Cárdenas Barroso
 * @info Proyecto Intermodular del Grado Superior DAM
 * @institution IES Augustóbriga
 */
public class DialogDetallesPresupuesto extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DialogDetallesPresupuesto.class.getName());

    private ControladorPresupuestos controlador;

    public void setControlador(ControladorPresupuestos controlador) {
        this.controlador = controlador; }
    
    /**
     * Creates new form DialogNuevoPresupuesto
     */
    public DialogDetallesPresupuesto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        // Aumentamos la velocidad del scroll (por defecto es muy lenta)
        scrollPrincipal.getVerticalScrollBar().setUnitIncrement(16);

        // Forzamos un tamaño mínimo para las tablas para que no se colapsen a 0px
        jScrollPane2.setMinimumSize(new java.awt.Dimension(500, 150)); 
        jScrollPane3.setMinimumSize(new java.awt.Dimension(500, 150));

        // Forzar recalculo visual
        panelContenido.revalidate();
        panelContenido.repaint();

        setLocationRelativeTo(parent);
        
        configurarListenersTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTitulo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        scrollPrincipal = new javax.swing.JScrollPane();
        panelContenido = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        btnNuevocliente = new javax.swing.JButton();
        lblVehiculo = new javax.swing.JLabel();
        cbxVehiculo = new javax.swing.JComboBox<>();
        lblEstado = new javax.swing.JLabel();
        cbxEstado = new javax.swing.JComboBox<>();
        lblFecha = new javax.swing.JLabel();
        spnFecha = new javax.swing.JSpinner();
        lblAveria = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAveria = new javax.swing.JTextArea();
        panelManoObra = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaManoObra = new javax.swing.JTable();
        panelMateriales = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMateriales = new javax.swing.JTable();
        panelResumen = new javax.swing.JPanel();
        lblBase = new javax.swing.JLabel();
        txtBase = new javax.swing.JTextField();
        lblIva = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        panelInferior = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelTitulo.setBackground(new java.awt.Color(33, 150, 243));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_apptaller_small.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("DETALLES DEL PRESUPUESTO");

        javax.swing.GroupLayout panelTituloLayout = new javax.swing.GroupLayout(panelTitulo);
        panelTitulo.setLayout(panelTituloLayout);
        panelTituloLayout.setHorizontalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(lblLogo)
                .addGap(200, 200, 200)
                .addComponent(lblTitulo)
                .addGap(0, 144, Short.MAX_VALUE))
        );
        panelTituloLayout.setVerticalGroup(
            panelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelTituloLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelTitulo, java.awt.BorderLayout.PAGE_START);

        panelContenido.setLayout(new javax.swing.BoxLayout(panelContenido, javax.swing.BoxLayout.Y_AXIS));

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Datos Generales"));

        lblCliente.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblCliente.setText("Cliente");

        cbxCliente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        btnNuevocliente.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnNuevocliente.setText("Nuevo");

        lblVehiculo.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblVehiculo.setText("Vehiculo");

        cbxVehiculo.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N

        lblEstado.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblEstado.setText("Estado");

        cbxEstado.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        cbxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pendiente", "aprobado" }));

        lblFecha.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblFecha.setText("Fecha");

        spnFecha.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        spnFecha.setModel(new javax.swing.SpinnerDateModel());

        lblAveria.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblAveria.setText("Avería");

        txtAveria.setColumns(20);
        txtAveria.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtAveria.setRows(5);
        jScrollPane1.setViewportView(txtAveria);

        javax.swing.GroupLayout panelDatosLayout = new javax.swing.GroupLayout(panelDatos);
        panelDatos.setLayout(panelDatosLayout);
        panelDatosLayout.setHorizontalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblAveria)
                    .addGroup(panelDatosLayout.createSequentialGroup()
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente)
                            .addGroup(panelDatosLayout.createSequentialGroup()
                                .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(btnNuevocliente)))
                        .addGap(53, 53, 53)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblVehiculo)
                            .addComponent(cbxVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEstado)
                            .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFecha)))
                    .addComponent(jScrollPane1))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelDatosLayout.setVerticalGroup(
            panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDatosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(lblVehiculo)
                    .addComponent(lblEstado)
                    .addComponent(lblFecha))
                .addGap(18, 18, 18)
                .addGroup(panelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevocliente)
                    .addComponent(cbxVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(lblAveria)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        panelContenido.add(panelDatos);

        panelManoObra.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Mano de obra"));

        tablaManoObra.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaManoObra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Descripción", "Horas", "Precio / Hora", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablaManoObra);

        javax.swing.GroupLayout panelManoObraLayout = new javax.swing.GroupLayout(panelManoObra);
        panelManoObra.setLayout(panelManoObraLayout);
        panelManoObraLayout.setHorizontalGroup(
            panelManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManoObraLayout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        panelManoObraLayout.setVerticalGroup(
            panelManoObraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelManoObraLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panelContenido.add(panelManoObra);

        panelMateriales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Materiales"));

        tablaMateriales.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tablaMateriales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Referencia", "Concepto", "Cantidad", "Precio Unidad", "Total"
            }
        ));
        jScrollPane3.setViewportView(tablaMateriales);

        javax.swing.GroupLayout panelMaterialesLayout = new javax.swing.GroupLayout(panelMateriales);
        panelMateriales.setLayout(panelMaterialesLayout);
        panelMaterialesLayout.setHorizontalGroup(
            panelMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialesLayout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );
        panelMaterialesLayout.setVerticalGroup(
            panelMaterialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMaterialesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        panelContenido.add(panelMateriales);

        panelResumen.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED), "Totales"));

        lblBase.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblBase.setText("Base Imponible");

        txtBase.setEditable(false);
        txtBase.setColumns(10);
        txtBase.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtBase.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblIva.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        lblIva.setText("IVA (21%)");

        txtIva.setEditable(false);
        txtIva.setColumns(10);
        txtIva.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        txtIva.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        lblTotal.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        lblTotal.setText("TOTAL");

        txtTotal.setEditable(false);
        txtTotal.setColumns(10);
        txtTotal.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        txtTotal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        javax.swing.GroupLayout panelResumenLayout = new javax.swing.GroupLayout(panelResumen);
        panelResumen.setLayout(panelResumenLayout);
        panelResumenLayout.setHorizontalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBase)
                    .addComponent(lblIva)
                    .addComponent(lblTotal))
                .addGap(125, 125, 125)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(202, Short.MAX_VALUE))
        );
        panelResumenLayout.setVerticalGroup(
            panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResumenLayout.createSequentialGroup()
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBase)
                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIva)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelResumenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelContenido.add(panelResumen);

        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        btnCancelar.setText("Cerrar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout panelInferiorLayout = new javax.swing.GroupLayout(panelInferior);
        panelInferior.setLayout(panelInferiorLayout);
        panelInferiorLayout.setHorizontalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInferiorLayout.createSequentialGroup()
                .addContainerGap(487, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(294, 294, 294))
        );
        panelInferiorLayout.setVerticalGroup(
            panelInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInferiorLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnCancelar)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelContenido.add(panelInferior);

        scrollPrincipal.setViewportView(panelContenido);

        getContentPane().add(scrollPrincipal, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose(); // Cierra el JDialog liberando memoria
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DialogDetallesPresupuesto dialog = new DialogDetallesPresupuesto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevocliente;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<String> cbxEstado;
    private javax.swing.JComboBox<String> cbxVehiculo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblAveria;
    private javax.swing.JLabel lblBase;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelInferior;
    private javax.swing.JPanel panelManoObra;
    private javax.swing.JPanel panelMateriales;
    private javax.swing.JPanel panelResumen;
    private javax.swing.JPanel panelTitulo;
    private javax.swing.JScrollPane scrollPrincipal;
    private javax.swing.JSpinner spnFecha;
    private javax.swing.JTable tablaManoObra;
    private javax.swing.JTable tablaMateriales;
    private javax.swing.JTextArea txtAveria;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables



    /**
     * Convierte el valor de una celda a BigDecimal de forma segura.
     */
    private java.math.BigDecimal parsearCelda(Object valor) {
        if (valor == null || valor.toString().trim().isEmpty()) {
            return java.math.BigDecimal.ZERO;
        }
        try {
            // Cambiamos coma por punto por si el usuario teclea formato europeo
            return new java.math.BigDecimal(valor.toString().replace(",", "."));
        } catch (NumberFormatException ex) {
            return java.math.BigDecimal.ZERO;
        }
    }

    
    /**
     * Recalcula el "Total" de una fila específica en la tabla de Mano de Obra
     */
    private void recalcularFilaManoObra(int fila) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaManoObra.getModel();
        
        // Columnas: [0] Desc, [1] Horas, [2] Precio/Hora, [3] Total
        java.math.BigDecimal horas = parsearCelda(modelo.getValueAt(fila, 1));
        java.math.BigDecimal precio = parsearCelda(modelo.getValueAt(fila, 2));
        
        java.math.BigDecimal subtotal = horas.multiply(precio);
        modelo.setValueAt(subtotal.toString(), fila, 3); // Actualizamos la columna Total
    }

    
    /**
     * Recalcula el "Total" de una fila específica en la tabla de Materiales
     */
    private void recalcularFilaMateriales(int fila) {
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaMateriales.getModel();
        
        // Columnas: [0] Ref, [1] Concepto, [2] Cantidad, [3] Precio, [4] Total
        java.math.BigDecimal cantidad = parsearCelda(modelo.getValueAt(fila, 2));
        java.math.BigDecimal precio = parsearCelda(modelo.getValueAt(fila, 3));
        
        java.math.BigDecimal subtotal = cantidad.multiply(precio);
        modelo.setValueAt(subtotal.toString(), fila, 4); // Actualizamos la columna Total
    }

    
    /**
     * Recorre ambas tablas, suma los totales y actualiza los JTextField inferiores.
     */
    private void calcularTotalesGlobales() {
        java.math.BigDecimal baseImponible = java.math.BigDecimal.ZERO;

        // Sumamos Mano de Obra (leemos la columna 3: Total)
        javax.swing.table.DefaultTableModel modManoObra = (javax.swing.table.DefaultTableModel) tablaManoObra.getModel();
        for (int i = 0; i < modManoObra.getRowCount(); i++) {
            baseImponible = baseImponible.add(parsearCelda(modManoObra.getValueAt(i, 3)));
        }

        // Sumamos Materiales (leemos la columna 4: Total)
        javax.swing.table.DefaultTableModel modMateriales = (javax.swing.table.DefaultTableModel) tablaMateriales.getModel();
        for (int i = 0; i < modMateriales.getRowCount(); i++) {
            baseImponible = baseImponible.add(parsearCelda(modMateriales.getValueAt(i, 4)));
        }

        // Calcular IVA (21%) y Total
        java.math.BigDecimal iva = baseImponible.multiply(new java.math.BigDecimal("0.21"));
        java.math.BigDecimal totalGeneral = baseImponible.add(iva);

        // Formatear a 2 decimales y mostrar en la interfaz
        // Usamos String.format para asegurar que siempre haya 2 decimales visualmente
        txtBase.setText(String.format("%.2f", baseImponible));
        txtIva.setText(String.format("%.2f", iva));
        txtTotal.setText(String.format("%.2f", totalGeneral));
    }
    
    
    /**
     * Configura los listeners para que las tablas reaccionen al editar celdas.
     */
    private void configurarListenersTablas() {
        // Listener para la tabla Mano de Obra
        tablaManoObra.getModel().addTableModelListener(new javax.swing.event.TableModelListener() {
            @Override
            public void tableChanged(javax.swing.event.TableModelEvent e) {
                if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
                    int columna = e.getColumn();
                    int fila = e.getFirstRow();
                    
                    // Si el usuario edita las Horas (1) o el Precio (2), recalculamos esa fila
                    if (columna == 1 || columna == 2) {
                        recalcularFilaManoObra(fila);
                    }
                }
                // Siempre que haya un cambio, recalculamos los totales de abajo
                calcularTotalesGlobales();
            }
        });

        // Listener para la tabla Materiales
        tablaMateriales.getModel().addTableModelListener(new javax.swing.event.TableModelListener() {
            @Override
            public void tableChanged(javax.swing.event.TableModelEvent e) {
                if (e.getType() == javax.swing.event.TableModelEvent.UPDATE) {
                    int columna = e.getColumn();
                    int fila = e.getFirstRow();
                    
                    // Si el usuario edita la Cantidad (2) o el Precio (3), recalculamos esa fila
                    if (columna == 2 || columna == 3) {
                        recalcularFilaMateriales(fila);
                    }
                }
                // Siempre que haya un cambio, recalculamos los totales de abajo
                calcularTotalesGlobales();
            }
        });
    }

    
    // Getters para que el Controlador acceda a la UI sin romper el encapsulamiento
    public javax.swing.JComboBox<String> getCbxCliente() { return cbxCliente; }
    public javax.swing.JComboBox<String> getCbxVehiculo() { return cbxVehiculo; }
    public javax.swing.JComboBox<String> getCbxEstado() { return cbxEstado; }
    public javax.swing.JSpinner getSpnFecha() { return spnFecha; }
    public javax.swing.JTextArea getTxtAveria() { return txtAveria; }
    public javax.swing.JTextField getTxtTotal() { return txtTotal; }
    public javax.swing.JTextField getTxtBase() {return txtBase; }
    public javax.swing.JTextField getTxtIva() {return txtIva; }
    public javax.swing.JTable getTablaManoObra() { return tablaManoObra; }
    public javax.swing.JTable getTablaMateriales() { return tablaMateriales; }

    
    
    /**
     * Carga todos los datos del presupuesto en la interfaz y bloquea la edición.
     */
    public void cargarDatos(int idPresupuesto) {
        PresupuestoDAO dao = new PresupuestoDAO();

        // Cargamos la cabecera
        PresupuestoVO cabecera = dao.obtenerPresupuestoPorId(idPresupuesto);
        if (cabecera != null) {
            // Como los combobox estarán bloqueados, simplemente metemos el dato como único ítem
            cbxCliente.removeAllItems();
            cbxCliente.addItem(cabecera.getClienteDni());
            
            cbxVehiculo.removeAllItems();
            cbxVehiculo.addItem(cabecera.getVehiculoBastidor());
            
            cbxEstado.removeAllItems();
            cbxEstado.addItem(cabecera.getEstado());
            
            txtAveria.setText(cabecera.getDescripcionTrabajo());
            txtTotal.setText(cabecera.getTotalEstimado().toString());
        }

        // Cargamos mano de obra
        javax.swing.table.DefaultTableModel modManoObra = (javax.swing.table.DefaultTableModel) tablaManoObra.getModel();
        modManoObra.setRowCount(0); // Vaciamos la tabla
        List<DetalleManoObraVO> manoObra = dao.obtenerManoObraPorPresupuesto(idPresupuesto);
        
        for (DetalleManoObraVO mo : manoObra) {
            modManoObra.addRow(new Object[]{
                mo.getDescripcionTrabajo(),
                mo.getTiempoEmpleadoHoras(),
                mo.getTarifaPorHora(),
                mo.getSubtotal()
            });
        }

        // Cargamos materiales
        javax.swing.table.DefaultTableModel modMateriales = (javax.swing.table.DefaultTableModel) tablaMateriales.getModel();
        modMateriales.setRowCount(0); // Vaciamos la tabla
        List<DetalleProductoVO> productos = dao.obtenerProductosPorPresupuesto(idPresupuesto);
        
        for (com.joseluis.apptaller.modelo.vo.DetalleProductoVO prod : productos) {
            modMateriales.addRow(new Object[]{
                prod.getIdProducto(),
                prod.getNombreProducto(),
                prod.getCantidadUsada(),
                prod.getPrecioVentaUnitario(),
                prod.getSubtotal()
            });
        }

        // Bloquear interfaz
        bloquearInterfaz();
    }

    
    /**
     * Congela todos los inputs para que el usuario no pueda modificar nada.
     */
    private void bloquearInterfaz() {
        cbxCliente.setEnabled(false);
        cbxVehiculo.setEnabled(false);
        cbxEstado.setEnabled(false);
        spnFecha.setEnabled(false);
        txtAveria.setEditable(false);
        
        // Deshabilitar la edición de las celdas de las tablas
        tablaManoObra.setEnabled(false);
        tablaMateriales.setEnabled(false);
    }
    
}
