
package com.joseluis.apptaller.vista.dialogos;

import com.joseluis.apptaller.controlador.ControladorReparaciones;
import com.joseluis.apptaller.modelo.dao.EmpleadoDAO;
import com.joseluis.apptaller.modelo.dao.PresupuestoDAO;
import com.joseluis.apptaller.modelo.vo.EmpleadoVO;
import com.joseluis.apptaller.modelo.vo.PresupuestoVO;
import com.joseluis.apptaller.modelo.vo.ReparacionVO;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Ventana de diálogo encargada de la recepción del vehículo y la creación de una 
 * nueva orden de reparación. Vincula automáticamente los datos de un presupuesto 
 * previamente aprobado y permite registrar la inspección de entrada (combustible, 
 * kilometraje, notas), así como asignar el mecánico responsable y la prioridad del trabajo.
 *
 * @author José Luis Cárdenas Barroso
 * @info Proyecto Intermodular del Grado Superior DAM
 * @institution IES Augustóbriga
 */
public class DialogNuevaReparacion extends javax.swing.JDialog {

    private int idPresupuestoVinculado;
    private String dniVinculado;
    private String bastidorVinculado;
    
    /**
     * Creates new form DialogNuevaReparacion
     */
    public DialogNuevaReparacion(java.awt.Frame parent, boolean modal, int idPresupuesto) {
        super(parent, modal);
        initComponents();
        setSize(600,700);
        setLocationRelativeTo(parent);
        
        this.idPresupuestoVinculado = idPresupuesto;
        
        cargarMecanicos(); // Solo cargamos los mecánicos para que el usuario elija
        cargarDatosFijosDelPresupuesto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenido = new javax.swing.JPanel();
        panelDatos = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        lblVehiculo = new javax.swing.JLabel();
        cbxVehiculo = new javax.swing.JComboBox<>();
        panelInspeccion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sldCombustible = new javax.swing.JSlider();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaDiagnostico = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNotas = new javax.swing.JTextField();
        spnKm = new javax.swing.JSpinner();
        panelAsignacion = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbxMecanico = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cbxPrioridad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        lblLogo = new javax.swing.JLabel();
        pnlTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        panelBotonesAccion = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JButton();
        btnCrearOrden = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recepción de Vehículo - Nueva Reparación");
        setModal(true);
        setPreferredSize(new java.awt.Dimension(600, 700));
        setSize(new java.awt.Dimension(800, 700));

        panelDatos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Cliente y Vehículo"));
        panelDatos.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        panelDatos.setLayout(new java.awt.GridLayout(2, 2, 10, 10));

        lblCliente.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblCliente.setText("Cliente");
        panelDatos.add(lblCliente);

        cbxCliente.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        panelDatos.add(cbxCliente);

        lblVehiculo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        lblVehiculo.setText("Vehículo");
        panelDatos.add(lblVehiculo);

        cbxVehiculo.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        panelDatos.add(cbxVehiculo);

        panelInspeccion.setBorder(javax.swing.BorderFactory.createTitledBorder("Inspección de Entrada"));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setText("Kilometraje");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setText("Combustible");

        sldCombustible.setMajorTickSpacing(25);
        sldCombustible.setPaintLabels(true);
        sldCombustible.setPaintTicks(true);

        txtAreaDiagnostico.setColumns(20);
        txtAreaDiagnostico.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        txtAreaDiagnostico.setLineWrap(true);
        txtAreaDiagnostico.setRows(5);
        jScrollPane2.setViewportView(txtAreaDiagnostico);

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setText("Descripción de la avería");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setText("Notas");

        txtNotas.setColumns(20);
        txtNotas.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        spnKm.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N

        javax.swing.GroupLayout panelInspeccionLayout = new javax.swing.GroupLayout(panelInspeccion);
        panelInspeccion.setLayout(panelInspeccionLayout);
        panelInspeccionLayout.setHorizontalGroup(
            panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInspeccionLayout.createSequentialGroup()
                .addGroup(panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(panelInspeccionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInspeccionLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(txtNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(sldCombustible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                    .addComponent(spnKm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelInspeccionLayout.setVerticalGroup(
            panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInspeccionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spnKm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sldCombustible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelInspeccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        panelAsignacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Asignación y Prioridad"));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel7.setText("Mecánico asignado");

        cbxMecanico.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cbxMecanico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMecanicoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel8.setText("Prioridad");

        cbxPrioridad.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        cbxPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baja", "Normal", "Alta", "Urgente" }));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel9.setText("Fecha estiamda entrega");

        jSpinner1.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jSpinner1.setModel(new javax.swing.SpinnerDateModel());

        javax.swing.GroupLayout panelAsignacionLayout = new javax.swing.GroupLayout(panelAsignacion);
        panelAsignacion.setLayout(panelAsignacionLayout);
        panelAsignacionLayout.setHorizontalGroup(
            panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignacionLayout.createSequentialGroup()
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addGap(60, 60, 60)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAsignacionLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSpinner1))
                    .addComponent(cbxMecanico, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbxPrioridad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelAsignacionLayout.setVerticalGroup(
            panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAsignacionLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbxMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(panelAsignacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_apptaller_titulo.png"))); // NOI18N

        pnlTitulo.setBackground(new java.awt.Color(33, 150, 243));

        lblTitulo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        lblTitulo.setText("ALTA / MODIFICACIÓN DE REPARACIONES");

        javax.swing.GroupLayout pnlTituloLayout = new javax.swing.GroupLayout(pnlTitulo);
        pnlTitulo.setLayout(pnlTituloLayout);
        pnlTituloLayout.setHorizontalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        pnlTituloLayout.setVerticalGroup(
            pnlTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTituloLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addComponent(panelInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenidoLayout.createSequentialGroup()
                        .addComponent(lblLogo)
                        .addGap(18, 18, 18)
                        .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelInspeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAsignacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        jScrollPane1.setViewportView(panelContenido);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        panelBotonesAccion.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        btnCancelar.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnCancelar.setText("Cancelar");
        panelBotonesAccion.add(btnCancelar);

        btnCrearOrden.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        btnCrearOrden.setText("Crear Orden Reparación");
        btnCrearOrden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearOrdenActionPerformed(evt);
            }
        });
        panelBotonesAccion.add(btnCrearOrden);

        getContentPane().add(panelBotonesAccion, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnCrearOrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearOrdenActionPerformed
        if (cbxMecanico.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "Debe asignar un mecánico a la orden.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        EmpleadoVO mecanicoSeleccionado = (EmpleadoVO) cbxMecanico.getSelectedItem();

        ReparacionVO rep = new ReparacionVO();

        // Datos que introduce el recepcionista
        rep.setKilometrajeEntrada((Integer) spnKm.getValue()); 
        
        int valorSlider = sldCombustible.getValue();
        String nivelSql = (valorSlider == 0) ? "Vacío" : (valorSlider <= 25) ? "1/4" : (valorSlider <= 50) ? "1/2" : (valorSlider <= 75) ? "3/4" : "Lleno";
        rep.setNivelCombustible(nivelSql);
        
        rep.setObservaciones(txtNotas.getText());
        rep.setPrioridad(cbxPrioridad.getSelectedItem().toString()); 
        
        // Datos bloqueados provenientes del presupuesto
        rep.setDiagnostico(txtAreaDiagnostico.getText()); 
        rep.setIdPresupuesto(idPresupuestoVinculado);
        rep.setClienteDni(dniVinculado); 
        rep.setVehiculoBastidor(bastidorVinculado);
        rep.setEmpleadoAsignadoId(mecanicoSeleccionado.getId_empleado()); 

        // Guardamos en la base de datos
        ControladorReparaciones ctrl = new ControladorReparaciones();
        if (ctrl.guardarNuevaReparacion(rep)) {
            JOptionPane.showMessageDialog(this, "¡Orden de Reparación creada con éxito!\nEl vehículo ya está en el taller.");
            this.dispose(); 
        } else {
            JOptionPane.showMessageDialog(this, "Error al guardar en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnCrearOrdenActionPerformed

    
    private void cbxMecanicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMecanicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMecanicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogNuevaReparacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNuevaReparacion dialog = new DialogNuevaReparacion(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearOrden;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<com.joseluis.apptaller.modelo.vo.EmpleadoVO> cbxMecanico;
    private javax.swing.JComboBox<String> cbxPrioridad;
    private javax.swing.JComboBox<String> cbxVehiculo;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblVehiculo;
    private javax.swing.JPanel panelAsignacion;
    private javax.swing.JPanel panelBotonesAccion;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JPanel panelDatos;
    private javax.swing.JPanel panelInspeccion;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JSlider sldCombustible;
    private javax.swing.JSpinner spnKm;
    private javax.swing.JTextArea txtAreaDiagnostico;
    private javax.swing.JTextField txtNotas;
    // End of variables declaration//GEN-END:variables

   
    private void cargarDatosFijosDelPresupuesto() {
        PresupuestoDAO pDao = new PresupuestoDAO();
        PresupuestoVO presu = pDao.obtenerPresupuestoPorId(idPresupuestoVinculado);

        if (presu != null) {
            // Guardamos las claves para usarlas al guardar
            this.dniVinculado = presu.getClienteDni();
            this.bastidorVinculado = presu.getVehiculoBastidor();

            // Mostramos los datos en los comboboxes y los bloqueamos
            cbxCliente.removeAllItems();
            cbxCliente.addItem(presu.getClienteDni()); 
            cbxCliente.setEnabled(false);

            cbxVehiculo.removeAllItems();
            cbxVehiculo.addItem(presu.getVehiculoBastidor());
            cbxVehiculo.setEnabled(false);

            txtAreaDiagnostico.setText(presu.getDescripcionTrabajo());
            txtAreaDiagnostico.setEditable(false);
        }
    }

    
    private void cargarMecanicos() {
        EmpleadoDAO empDao = new EmpleadoDAO();
        List<EmpleadoVO> empleados = empDao.listarMecanicosActivos();
        cbxMecanico.removeAllItems();
        for (EmpleadoVO e : empleados) {
            cbxMecanico.addItem(e); 
        }
    }
    

}
